upstream my_service {
  server blablabook-client:${PORT};
}

server {
  listen ${PORT:-80};

  server_name blablabook-client.onrender.com;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
} 